name: WB Stocks to Supabase (every 30m)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Jitter start (0–40s)
        run: |
          S=$((RANDOM % 41))
          echo "Sleeping for $S seconds to avoid API burst..."
          sleep $S

      - name: Run job
        env:
          WB_ANALYTICS_TOKEN: ${{ secrets.WB_ANALYTICS_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_TABLE: wb_stocks_current

          # ВКЛЮЧАЕМ технические строки (если нужны — ставь "false")
          EXCLUDE_TOTAL_ROW: "false"     # вернуть «Всего находится на складах»
          EXCLUDE_IN_TRANSIT: "false"    # вернуть «В пути ...»
          EXCLUDE_RETURNS: "false"       # вернуть «...возврат...»

          # Тюнинг лимитов WB
          WB_STATUS_POLL_INTERVAL_SEC: "5"
          WB_STATUS_TIMEOUT_SEC: "600"
          WB_DOWNLOAD_COOLDOWN_SEC: "70"
          WB_DOWNLOAD_MAX_RETRIES: "8"
        run: |
          python wb_stocks_current_job.py
